## Importation des Donnes

In [16]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv('train_set.csv')
data=data.drop(['moyeneGeneral','Note1', 'Note2', 'Note3','Note4', 'Note5', 'Note6', 'Note7', 'Note8','Nom','ID'],axis=1)
data.head()

Unnamed: 0 Serie,x GroupeAnonymat   LieuNaissance              Centre  \
0       27634      SN           SN09     Bathet meit        Lycée Jedida   
1       36311      LO            LO1   Beir Taouress  Lycée Arafat 2 (A)   
2       21059      LM            LM3         Akjoujt       Lycée Akjoujt   
3       24532      SN           SN06  Chelkhet Tiyab  Lycée Toujounine 1   
4       17861      SN           SN03      Aere M'Bar  Lycée Nouadhibou 2   

           Etablissement Decision               Willaya   moughataa  \
0           Lycée Jedida  Ajourné  Nouakchott 2 (Ouest)        KSAR   
1         Lycée Arafat 2  Ajourné    Nouakchott 3 (Sud)      ARAFAT   
2          Lycée Akjoujt  Ajourné               Inchiri     AKJOUJT   
3     Lycée Toujounine 1  Ajourné   Nouakchott 1 (Nord)  TOUJOUNINE   
4  Lycée Wava Nouadhibou  Ajourné           Dakhlet NDB  NOUADHIBOU   

    DateNaissance  
0  12 ديسمبر 1998  
1  26 ديسمبر 1991  
2     8 مايو 1995  
3    24 avr. 1999  
4     10 mai 2001

## Preprocessing

In [3]:
### creer une colonne pour connaitre l'age
data['age'] = data['DateNaissance'].apply(  
    lambda x: int(x.split("-")[2] if '-' in x else int(x.split(" ")[2]) )
    ).apply(lambda x : 2021 - x if x > 1900  else ( 121 - x if x > 21 else 21 - x))

In [8]:
data=data.drop('DateNaissance',axis=1)

In [4]:
data=data.drop('Unnamed: 0',axis=1)

In [6]:
# Transformer les observations
data['Decision'] = data['Decision'].replace(['Ajourné', 'Sessionnaire', 'Abscent', 'Examen annulé à cause du Téléphone', 'Examen annulé à cause du comportement'], 'Ajourné')

In [7]:
### encoder la variable target 
data['Decision']=pd.get_dummies(data['Decision'],drop_first=True)
data.head()

Serie,x GroupeAnonymat   LieuNaissance              Centre  \
0      SN           SN09     Bathet meit        Lycée Jedida   
1      LO            LO1   Beir Taouress  Lycée Arafat 2 (A)   
2      LM            LM3         Akjoujt       Lycée Akjoujt   
3      SN           SN06  Chelkhet Tiyab  Lycée Toujounine 1   
4      SN           SN03      Aere M'Bar  Lycée Nouadhibou 2   

           Etablissement  Decision               Willaya   moughataa  \
0           Lycée Jedida         1  Nouakchott 2 (Ouest)        KSAR   
1         Lycée Arafat 2         1    Nouakchott 3 (Sud)      ARAFAT   
2          Lycée Akjoujt         1               Inchiri     AKJOUJT   
3     Lycée Toujounine 1         1   Nouakchott 1 (Nord)  TOUJOUNINE   
4  Lycée Wava Nouadhibou         1           Dakhlet NDB  NOUADHIBOU   

    DateNaissance  age  
0  12 ديسمبر 1998   23  
1  26 ديسمبر 1991   30  
2     8 مايو 1995   26  
3    24 avr. 1999   22  
4     10 mai 2001   20

In [9]:
data.head()

Serie,x GroupeAnonymat   LieuNaissance              Centre  \
0      SN           SN09     Bathet meit        Lycée Jedida   
1      LO            LO1   Beir Taouress  Lycée Arafat 2 (A)   
2      LM            LM3         Akjoujt       Lycée Akjoujt   
3      SN           SN06  Chelkhet Tiyab  Lycée Toujounine 1   
4      SN           SN03      Aere M'Bar  Lycée Nouadhibou 2   

           Etablissement  Decision               Willaya   moughataa  age  
0           Lycée Jedida         1  Nouakchott 2 (Ouest)        KSAR   23  
1         Lycée Arafat 2         1    Nouakchott 3 (Sud)      ARAFAT   30  
2          Lycée Akjoujt         1               Inchiri     AKJOUJT   26  
3     Lycée Toujounine 1         1   Nouakchott 1 (Nord)  TOUJOUNINE   22  
4  Lycée Wava Nouadhibou         1           Dakhlet NDB  NOUADHIBOU   20

## Preparer les donnes pour le modele

In [10]:
# Sélection des variables catégorielles et numériques
cat_vars = ['Serie,x', 'GroupeAnonymat', 'LieuNaissance', 'Centre', 'Etablissement', 'Willaya', 'moughataa']
num_vars = ['age']


In [12]:
# Sélection des données d'entraînement
train_data = data[cat_vars + num_vars]
train_target = data['Decision']


In [14]:
# Encodage des variables catégorielles
encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
X = encoder.fit_transform(train_data[cat_vars])

In [17]:
# Concaténation des données catégorielles et numériques
X = np.concatenate([X, train_data[num_vars]], axis=1)

## Entrainement du modele

In [19]:
# Séparation des données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, train_target, test_size=0.2, random_state=42)

In [20]:
# Instanciation et entraînement du modèle de régression logistique
clf = LogisticRegression()
clf.fit(X_train, y_train)

C:\Users\TOSHIBA\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [21]:
# Évaluation du modèle sur les données de test
score = clf.score(X_test, y_test)
print(f"Score : {score}")

Score : 0.9240426867545511


In [22]:
y_pred = clf.predict(X_test)

In [23]:
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=uint8)

## tester le modele sur les donnes de submission_template 

### Creation du dataset new_data

In [24]:
### Importation
test=pd.read_csv('test_set.csv',sep=';',index_col='ID')
test=test.drop(["Unnamed: 0",'prediction'],axis=1)

In [25]:
test.head()

Nom Serie,x GroupeAnonymat LieuNaissance  \
ID                                                                          
ID_6         Mohamed Hama Ahmed Lely      SN           SN09       Vassala   
ID_15     Fatimatou Mohamed Sid Abbe      SN           SN09       Vassala   
ID_18  El Alye Cheikh Ahmed Maihmatt      SN           SN09       Vassala   
ID_19      Haine Mohamed Lemin Telba      SN           SN09       Vassala   
ID_20    Aichata Sid'Ahmed Ahmed Ely      SN           SN09      El Megve   

              Centre  Etablissement      Willaya  moughataa  DateNaissance  
ID                                                                          
ID_6   Lycée Vassala  Lycée Vassala  Hod Charghy  BASSEKNOU  15 يوليو 2001  
ID_15  Lycée Vassala  Lycée Vassala  Hod Charghy  BASSEKNOU   12 août 1999  
ID_18  Lycée Vassala  Lycée Vassala  Hod Charghy  BASSEKNOU  18 sept. 1999  
ID_19  Lycée Vassala  Lycée Vassala  Hod Charghy  BASSEKNOU   24 août 1998  
ID_20  Lycée Vassala  Lycée Vassala  Hod Charghy  BASSEKNOU      31-mai-95

In [27]:
test['age'] = test['DateNaissance'].apply(  
    lambda x: int(x.split("-")[2] if '-' in x else int(x.split(" ")[2]) )
    ).apply(lambda x : 2021 - x if x > 1900  else ( 121 - x if x > 21 else 21 - x))

In [29]:
test=test.drop("DateNaissance",axis=1)

In [30]:
test.head()

Nom Serie,x GroupeAnonymat LieuNaissance  \
ID                                                                          
ID_6         Mohamed Hama Ahmed Lely      SN           SN09       Vassala   
ID_15     Fatimatou Mohamed Sid Abbe      SN           SN09       Vassala   
ID_18  El Alye Cheikh Ahmed Maihmatt      SN           SN09       Vassala   
ID_19      Haine Mohamed Lemin Telba      SN           SN09       Vassala   
ID_20    Aichata Sid'Ahmed Ahmed Ely      SN           SN09      El Megve   

              Centre  Etablissement      Willaya  moughataa  age  
ID                                                                
ID_6   Lycée Vassala  Lycée Vassala  Hod Charghy  BASSEKNOU   20  
ID_15  Lycée Vassala  Lycée Vassala  Hod Charghy  BASSEKNOU   22  
ID_18  Lycée Vassala  Lycée Vassala  Hod Charghy  BASSEKNOU   22  
ID_19  Lycée Vassala  Lycée Vassala  Hod Charghy  BASSEKNOU   23  
ID_20  Lycée Vassala  Lycée Vassala  Hod Charghy  BASSEKNOU   26

In [31]:
data1=pd.read_csv('train_set.csv',index_col='ID')
data1=data1.drop(["Unnamed: 0",'moyeneGeneral','Note1', 'Note2', 'Note3','Note4', 'Note5', 'Note6', 'Note7', 'Note8'],axis=1)
data1.head()

Nom Serie,x GroupeAnonymat   LieuNaissance  \
ID                                                                            
ID_27634        El Ide Brahim M'Hadi      SN           SN09     Bathet meit   
ID_36311         Mariem Yedaly Afane      LO            LO1   Beir Taouress   
ID_21059           Aiche Jiyid Jiyid      LM            LM3         Akjoujt   
ID_24532  Ahmed Abd El Ghader Meissa      SN           SN06  Chelkhet Tiyab   
ID_17861         Mariam Abdoulaye Ba      SN           SN03      Aere M'Bar   

                      Centre          Etablissement Decision  \
ID                                                             
ID_27634        Lycée Jedida           Lycée Jedida  Ajourné   
ID_36311  Lycée Arafat 2 (A)         Lycée Arafat 2  Ajourné   
ID_21059       Lycée Akjoujt          Lycée Akjoujt  Ajourné   
ID_24532  Lycée Toujounine 1     Lycée Toujounine 1  Ajourné   
ID_17861  Lycée Nouadhibou 2  Lycée Wava Nouadhibou  Ajourné   

                       Willaya   moughataa   DateNaissance  
ID                                                          
ID_27634  Nouakchott 2 (Ouest)        KSAR  12 ديسمبر 1998  
ID_36311    Nouakchott 3 (Sud)      ARAFAT  26 ديسمبر 1991  
ID_21059               Inchiri     AKJOUJT     8 مايو 1995  
ID_24532   Nouakchott 1 (Nord)  TOUJOUNINE    24 avr. 1999  
ID_17861           Dakhlet NDB  NOUADHIBOU     10 mai 2001

In [32]:
data1['age'] = data1['DateNaissance'].apply(  
    lambda x: int(x.split("-")[2] if '-' in x else int(x.split(" ")[2]) )
    ).apply(lambda x : 2021 - x if x > 1900  else ( 121 - x if x > 21 else 21 - x))

In [33]:
data1=data1.drop("DateNaissance",axis=1)

In [34]:
data1=data1.drop("Decision",axis=1)

In [35]:
new=pd.concat([test,data1],axis=0)

In [66]:
#new=new.reset_index()
#sub=pd.read_csv('submission_template.csv')
#new = new[new.ID.isin(sub.Id)]
#new.to_csv('new_data.csv')

In [41]:
new=pd.read_csv('new_data.csv')
new=new.drop('Unnamed: 0',axis=1)
new=new.drop('prediction',axis=1)

In [42]:
new

ID                                       Nom Serie,x  \
0         ID_15                Fatimatou Mohamed Sid Abbe      SN   
1         ID_22         Zahra Sid Ahmed Ahmed Leely Jamaa      SN   
2         ID_23            Fatimatou Khatary Sidi Mohamed      SN   
3         ID_29                   Mesouda Zeidan M'Bareck      SN   
4         ID_34  Mohamed Mahmoude Mohamed Abdellahi Deyar      SN   
...         ...                                       ...     ...   
15925  ID_13569              Oum El Vadli Messoud Messoud      LM   
15926  ID_31670                           Djama Sidi Sidi      LM   
15927  ID_31759               Ahmed Mohameden El Moustaph      LO   
15928   ID_5855                   Saleck El Khacha Saleck      LM   
15929  ID_13889                    Ebou Taleb Samba Salem      SN   

      GroupeAnonymat LieuNaissance                       Centre  \
0               SN09       Vassala                Lycée Vassala   
1               SN09       Vassala                Lycée Vassala   
2               SN09       Vassala                Lycée Vassala   
3               SN09       Vassala                Lycée Vassala   
4               SN09       Vassala                Lycée Vassala   
...              ...           ...                          ...   
15925            LM5    Boutilimit           Collége Boutimit 2   
15926            LM4        Arafat  Ecole Sidi Abdoullah-Arafat   
15927            LO3         Riyad           Lycée Arafat 3 (A)   
15928            LM1         Kiffa                Lycée Kiffa 3   
15929           SN08        Tekane            Lycée Boutilimitt   

                Etablissement             Willaya    moughataa  age  
0               Lycée Vassala         Hod Charghy    BASSEKNOU   22  
1               Lycée Vassala         Hod Charghy    BASSEKNOU   18  
2               Lycée Vassala         Hod Charghy    BASSEKNOU   18  
3               Lycée Vassala         Hod Charghy    BASSEKNOU   21  
4               Lycée Vassala         Hod Charghy    BASSEKNOU   21  
...                       ...                 ...          ...  ...  
15925    Collége Boutilimit 2              Trarza  BOUTILIMITT   22  
15926  Candidats Libres Riyad  Nouakchott 3 (Sud)       RIYADH   24  
15927  Candidats Libres Riyad  Nouakchott 3 (Sud)       RIYADH   22  
15928            Lycee Kifa 1              Assaba        KIFFA   18  
15929       Lycée Boutilimitt              Trarza  BOUTILIMITT   26  

[15930 rows x 10 columns]

In [49]:
cat_vars2 = [ 'Serie,x', 'GroupeAnonymat', 'LieuNaissance', 'Centre', 'Etablissement', 'Willaya', 'moughataa']
num_vars2 = ['age']
test_data2 = new[cat_vars2 + num_vars2]


In [50]:
# encoder les variables categorielles 
X2 = encoder.transform(test_data2[cat_vars2])

In [52]:
# Concaténation des données catégorielles et numériques
X2 = np.concatenate([X2, test_data2[num_vars2]], axis=1)

In [53]:
y_pred2 = clf.predict(X2)

In [54]:
y_pred2

array([1, 1, 1, ..., 1, 1, 1], dtype=uint8)

In [56]:
g=pd.DataFrame(y_pred2)
g.value_counts()

1    15711
0      219
dtype: int64

In [57]:
#trouver la probabilite d'admissiom
proba=clf.predict_proba(X2)

In [58]:
proba

array([[0.02483346, 0.97516654],
       [0.05612557, 0.94387443],
       [0.05612557, 0.94387443],
       ...,
       [0.01027946, 0.98972054],
       [0.03814835, 0.96185165],
       [0.01033953, 0.98966047]])

In [60]:
pre=proba[:, 0]
len(pre)

15930

In [61]:
new['prediction']=pre

In [62]:
submission=new[['ID','prediction']]

In [63]:
submission

ID  prediction
0         ID_15    0.024833
1         ID_22    0.056126
2         ID_23    0.056126
3         ID_29    0.030519
4         ID_34    0.030519
...         ...         ...
15925  ID_13569    0.013048
15926  ID_31670    0.006452
15927  ID_31759    0.010279
15928   ID_5855    0.038148
15929  ID_13889    0.010340

[15930 rows x 2 columns]

In [64]:
submission.to_csv('regression_logistique.csv',index=False)